### PR TITLE
FAQ Feature added

### LINKED ISSUE #10: Feature: Implement FAQ Section
## Description 

To enhance user experience, I propose adding a Frequently Asked Questions (FAQ) section to the STEAM app. This section will offer quick access to information on satellite tracking, Liquid Galaxy rig usage, and common troubleshooting. The goal is to empower users with easily accessible answers, streamlining support and contributing to an informed and positive app experience.

The FAQ section aims to improve user support, reducing the need for external assistance. Users will find quick solutions to common queries, fostering a sense of empowerment and satisfaction. This addition aligns with our commitment to providing a user-centric and informative app.

### PR DESCRIPTION
**Pull request by andoriyaprashant**
## Description

This pull request introduces the FAQ (Frequently Asked Questions) feature to enhance user understanding and provide helpful information about the STEAM Celestial Satellite Tracker app. The FAQ section covers various topics related to the app's functionality, setup, and usage.

## Changes Made

- Added a new FAQ screen with a list of common questions and answers.
- Updated the app's theme to ensure a cohesive and visually appealing design.
- Included relevant content to address user queries about the app.

## Demo video

https://github.com/savitore/STEAM-Celestial-Satellite-tracker-in-real-time/assets/121665385/2c829aa1-b8a3-4ab7-b9af-d12acd63e850

## Checklist

- [X] I have tested the FAQ feature thoroughly on multiple devices.
- [X] The code adheres to the project's coding standards and guidelines.
- [X] Documentation has been updated to include information about the new FAQ feature.
- [X] All new and existing unit tests pass successfully.

### CODE REVIEW

**Comment by savitore** [comment]
@andoriyaprashant UI is not good, match the theme of this page with the app.

**Comment by andoriyaprashant** [comment]
Hello @savitore I've made some changes to the UI
could you please review them? I'll be uploading some screenshots shortly

WhatsApp Image 2024-01-06 at 17 08 47_6113b4cf
WhatsApp Image 2024-01-06 at 17 08 55_ad840ea5

**Comment by savitore** [comment]
@andoriyaprashant, please change the colour of the tiles and use a colour that matches the app's UI. Also, in the Settings page, add a line above the FAQ option to match with the UI.

**Comment by andoriyaprashant** [comment]
@savitore as you instructed, I have made changes to the UI. I tried fixing the FAQ page UI by adding a red border around the white tiles. Additionally, under the settings, I added a border below the help section. You can see these changes in the screenshots.

WhatsApp Image 2024-01-11 at 22 52 29_6971c875

WhatsApp Image 2024-01-11 at 22 52 42_e7fec8aa


 Thank you.

**Comment by savitore** [comment]
@andoriyaprashant don't add red border, please. what I meant was change background colour.

**Comment by andoriyaprashant** [comment]
I will remove it right away, sir @savitore

**Comment by andoriyaprashant** [comment]
Done @savitore Sir I removed the red border, and changed the color of the tiles to white. If you want any other color, please specify, and I will use that Thank you 
WhatsApp Image 2024-01-11 at 23 09 52_04e7aec9

**Comment by savitore** [comment]
this is fine. thanks.

**Pull request merged**
