### PR TITLE
Added Clear Button

### PR DESCRIPTION
**Pull request by yash-jain-1**
simple clear button which displays all the data again after the search field has been cleared.

### CODE REVIEW

**Comment by yash-jain-1** [comment]
@savitore Is this ok? I have added the button

**Comment by savitore** [comment]
please provide apk @yash-jain-1

**Comment by savitore** [comment]
please provide apk @yash-jain-1

**Comment by yash-jain-1** [comment]
@savitore sure

**Comment by yash-jain-1** [comment]
> please provide apk @yash-jain-1

There is an issue I am facing while building the apk
image
I tried resolving the issue by updating the kotlin version but the problem still persists

**Comment by savitore** [comment]
@andoriyaprashant please help @yash-jain-1

**Pull request closed without merging**
